### ISSUE TITLE
 ERROR: no such package '@io_kythe//kythe/data': The repository '@io_kythe' could not be resolved: Repository '@io_kythe' is not defined

### ISSUE THREAD

**Issue by sgowroji** [kythe/kythe#5921] opened 2023-11-08 12:40 UTC
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3445#018bacb6-76dc-4f11-97ea-3a5436823a8b

Platform : ubuntu2004

Logs:
```
ERROR: no such package '@io_kythe//kythe/data': The repository '@io_kythe' could not be resolved: Repository '@io_kythe' is not defined
(02:28:08) ERROR: /var/lib/buildkite-agent/builds/bk-docker-pr70/bazel-downstream-projects/kythe/WORKSPACE:63:19: no such package '@io_kythe//kythe/data': The repository '@io_kythe' could not be resolved: Repository '@io_kythe' is not defined and referenced by '//external:vnames_config'
Target //kythe/java/com/google/devtools/kythe/analyzers/base:corner_case_srcs failed to build
(02:28:08) ERROR: Analysis of target '//kythe/cxx/indexer/textproto/plugins/example/testdata:cross_file_test_test1_entries' failed; build aborted: Analysis failed
```

Steps:
```
git clone https://github.com/kythe/kythe.git
git reset a7d94adb2131b8fe6c53f2a4678749e7552e7d51 --hard
export USE_BAZEL_VERSION=6a08b2f8a2a2c4efb5ffb5c626ab73728772d9a6
sudo apt update && sudo apt -y install bison flex uuid-dev asciidoc graphviz source-highlight
bazel build //kythe/...
```

CC Greenteam @Wyverald

**Comment by shahms** [comment] 2023-11-09 17:20
This is almost certainly a duplicate of #5893

**Closed by shahms** 2023-11-09 17:20 UTC
