### ISSUE TITLE
Add support for Go modules in the Go extractor

### ISSUE THREAD

**Issue by creachadair** [kythe/kythe#3334] opened 2018-12-19 18:24 UTC
Go 1.11 added support for a new package organization scheme called "modules", and subsequent versions will extend this (see https://blog.golang.org/modules2019) with the goal of replacing the existing `GOPATH` mechanism by the end of 2019. 

The "native" Go extractor should be able to extract compilation records from module builds, even if a `GOPATH` is not available. At minimum this will probably require integrating with the [golang.org/x/tools/go/packages](http://godoc.org/golang.org/x/tools/go/packages) package, and possibly some other shenanigans.

**Comment by schroederc** [comment] 2018-12-21 18:47
Duplicate of #2881

**Closed by schroederc** 2018-12-21 18:47 UTC

**Comment by creachadair** [comment] 2018-12-21 18:57
Oops, sorry I missed the earlier one.
