### ISSUE TITLE
kythe xrefs crash with -api tables

### ISSUE THREAD

**Issue by kamahen** [kythe/kythe#4248] opened 2019-12-10 00:24 UTC
`kythe nodes` works with either the tables or the server.
`kythe xrerfs works with the server but crashes with the tables.
The following traceback is with the latest pull (2019-12-09 16:20 Pacific Time).
```
$ ../kythe/bazel-bin/kythe/go/serving/tools/kythe/kythe -api /tmp/pykythe_test/tables xrefs 'kythe://test-corpus?lang=python?root=test-root#.tmp.pykythe_test.SUBST.home.peter.src.pykythe.pykythe.pod.PlainOldData'
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x85e446]

goroutine 1 [running]:
kythe.io/kythe/go/serving/xrefs.nodeKind(0x0, 0xc00009e380, 0x76)
	kythe/go/serving/xrefs/xrefs.go:735 +0x26
kythe.io/kythe/go/serving/xrefs.(*Table).CrossReferences(0xc00005b040, 0xa77ce0, 0xc000026140, 0xc000106000, 0x0, 0x0, 0x0)
	kythe/go/serving/xrefs/xrefs.go:556 +0x58e
kythe.io/kythe/go/serving/api.apiCloser.CrossReferences(...)
	kythe/go/serving/api/api.go:158
kythe.io/kythe/go/services/cli.xrefsCommand.Run(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x9c3bfe, 0x7, 0x9c1205, ...)
	kythe/go/services/cli/commands_xrefs.go:130 +0x294
kythe.io/kythe/go/services/cli.(*commandWrapper).Execute(0xc00005b190, 0xa77ce0, 0xc000026140, 0xc0000707e0, 0xc00005b1a0, 0x1, 0x1, 0x7f0f3790b008)
	kythe/go/services/cli/cli.go:107 +0x149
github.com/google/subcommands.(*Commander).Execute(0xc0000e4d20, 0xa77ce0, 0xc000026140, 0xc00005b1a0, 0x1, 0x1, 0x1)
	external/com_github_google_subcommands/subcommands.go:142 +0x2f9
github.com/google/subcommands.Execute(...)
	external/com_github_google_subcommands/subcommands.go:420
kythe.io/kythe/go/services/cli.Execute(0xa77ce0, 0xc000026140, 0x7f0f378cf0c0, 0xc000020690, 0x7f0f378cf0f0, 0xc000020690, 0x7f0f378cf118, 0xc000020690, 0x7f0f378cf140, 0xc000020690, ...)
	kythe/go/services/cli/cli.go:84 +0x70d
main.main()
	kythe/go/serving/tools/kythe/kythe.go:60 +0x246
```

However, this works when accessing the server:
```
$ ../kythe/bazel-bin/kythe/go/serving/tools/kythe/kythe -api http://localhost:8080 xrefs 'kythe://test-corpus?lang=python?root=test-root#.tmp.pykythe_test.SUBST.home.peter.src.pykythe.pykythe.pod.PlainOldData'
Cross-References for kythe://test-corpus?lang=python?root=test-root#.tmp.pykythe_test.SUBST.home.peter.src.pykythe.pykythe.pod.PlainOldData
  Definitions:
    tmp/pykythe_test/SUBST/home/peter/src/pykythe/pykythe/pod.py	    [16:6-16:18)
      "class PlainOldData:"
  References:
    tmp/pykythe_test/SUBST/home/peter/src/pykythe/pykythe/ast.py	    [22:15-22:27)
      "class File(pod.PlainOldData):"
    tmp/pykythe_test/SUBST/home/peter/src/pykythe/pykythe/pod.py	    [37:27-37:39)
      "class PlainOldDataExtended(PlainOldData):"
    tmp/pykythe_test/SUBST/home/peter/src/pykythe/pykythe/pod.py	    [57:21-57:33)
      "        value: Union[PlainOldData, List[Any], bool, str, int, Dict[Any, Any], None,"
    tmp/pykythe_test/SUBST/home/peter/src/pykythe/pykythe/pod.py	    [61:25-61:37)
      "    if isinstance(value, PlainOldData):"
    tmp/pykythe_test/SUBST/home/peter/src/pykythe/pykythe/ast_raw.py	    [83:14-83:26)
      "class Ctx(pod.PlainOldData):"
    tmp/pykythe_test/SUBST/home/peter/src/pykythe/pykythe/ast_cooked.py	    [92:17-92:29)
      "class FqnCtx(pod.PlainOldData):"
```

**Comment by isker** [comment] 2019-12-10 02:17
Seems like the same crash as #4128

**Comment by isker** [comment] 2019-12-10 14:57
FWIW repeating my example from #4128 but with the HTTP server resulted in the same failure:

```
2019/12/10 14:55:00 http: panic serving x.x.x.x:33028: runtime error: invalid memory address or nil pointer dereference
goroutine 59 [running]:
net/http.(*conn).serve.func1(0xc0000b8e60)
	GOROOT/src/net/http/server.go:1767 +0x139
panic(0x9756a0, 0xe4cce0)
	GOROOT/src/runtime/panic.go:679 +0x1b2
kythe.io/kythe/go/serving/xrefs.nodeKind(0x0, 0xc000178460, 0x95)
	kythe/go/serving/xrefs/xrefs.go:735 +0x26
kythe.io/kythe/go/serving/xrefs.(*Table).CrossReferences(0xc00009b2a0, 0xae3420, 0xc0000a4000, 0xc00018e480, 0xc0000ae180, 0xc0003f2b00, 0xae1a20)
	kythe/go/serving/xrefs/xrefs.go:556 +0x58e
kythe.io/kythe/go/services/xrefs.BoundedRequests.CrossReferences(0x14, 0xae0360, 0xc00009b2a0, 0xae3420, 0xc0000a4000, 0xc00018e480, 0x0, 0x29772e01, 0xc00018e480)
	kythe/go/services/xrefs/xrefs.go:250 +0x134
kythe.io/kythe/go/services/xrefs.RegisterHTTPHandlers.func1(0xae2420, 0xc0000f42a0, 0xc00018a400)
	kythe/go/services/xrefs/xrefs.go:312 +0x138
net/http.HandlerFunc.ServeHTTP(0xc000120780, 0xae2420, 0xc0000f42a0, 0xc00018a400)
	GOROOT/src/net/http/server.go:2007 +0x44
net/http.(*ServeMux).ServeHTTP(0xc0000c8700, 0xae2420, 0xc0000f42a0, 0xc00018a400)
	GOROOT/src/net/http/server.go:2387 +0x1bd
main.main.func1(0xae2420, 0xc0000f42a0, 0xc00018a400)
	kythe/go/serving/tools/http_server/http_server.go:108 +0x5d
net/http.HandlerFunc.ServeHTTP(0xc00009b300, 0xae2420, 0xc0000f42a0, 0xc00018a400)
	GOROOT/src/net/http/server.go:2007 +0x44
net/http.(*ServeMux).ServeHTTP(0xea5400, 0xae2420, 0xc0000f42a0, 0xc00018a400)
	GOROOT/src/net/http/server.go:2387 +0x1bd
net/http.serverHandler.ServeHTTP(0xc00013e000, 0xae2420, 0xc0000f42a0, 0xc00018a400)
	GOROOT/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc0000b8e60, 0xae33e0, 0xc0000c8800)
	GOROOT/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	GOROOT/src/net/http/server.go:2927 +0x38e
```

**Comment by shahms** [comment] 2019-12-10 17:58
I believe this is a duplicate of #4128

**Closed by shahms** 2019-12-10 17:58 UTC
Labels: duplicate
